name: auto-recoder
on: 
  pull_request:
permissions:
  contents: write
  
jobs:
  auto-recode:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: do work
      run: |
        script=$(cat <<EOF
        pr_number = ${{github.event.pull_request.number}} 
        print(pr_number)
        print("${{github.event.pull_request.title}}")
        #pr_title_feat = str(${{github.event.pull_request.title}})
        """
        index = pr_title_feat.find(":")

        new_title = pr_number + "." + pr_title_feat[0:index] + ".md"
        file = open("/home/runner/work/backend.ai/backend.ai/changes/"+new_title, "w")

        file.write(" ".join(['this','is','constant']))
        file.close()
        """
        EOF
        )
        echo "$script" | python

    - name: commit message for adding change log file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: GitHub Actions added ${{github.event.pull_request.number}}.YOUR_PR_FEAT.md file in backend.ai/changes folder and its content is your PR's title without feature.