name: auto-recode

on: 
  pull_request:

jobs:
  auto-recode:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} # pull request를 요청한 branch 이름

    - name: Check if temp.txt and .md file exist
      run: |
        if [ -f "/home/runner/work/backend.ai/backend.ai/changes/temp.txt" ] && [ -f "/home/runner/work/backend.ai/backend.ai/changes/*.md" ]; then
          echo "Error: temp.txt and .md file both exist"
          exit 1
        elif [ -f "/home/runner/work/backend.ai/backend.ai/changes/temp.txt" ] && [ ! -f "/home/runner/work/backend.ai/backend.ai/changes/*.md" ]; then
            script=$(cat <<EOF
            import sys
            import os
            pr_number = sys.argv[1]
            pr_title_feat = sys.argv[2]

            index = pr_title_feat.find(":")

            new_title = pr_number + "." + pr_title_feat[0:index] + ".md"
            os.rename("text.txt", new_title)

            EOF
            )
            echo "$script" | python - ${{github.event.pull_request.number}} ${{github.event.pull_request.title}}
        elif [ ! -f "/home/runner/work/backend.ai/backend.ai/changes/temp.txt" ] && [ -f "/home/runner/work/backend.ai/backend.ai/changes/*.md" ]; then
            script=$(cat <<EOF
            import sys
            import os
            pr_number = sys.argv[1]
            pr_title_feat = sys.argv[2]

            index = pr_title_feat.find(":")

            new_title = pr_number + "." + pr_title_feat[0:index] + ".md"
            if()
            os.rename("text.txt", new_title)

            EOF
            )
            echo "$script" | python - ${{github.event.pull_request.number}} ${{github.event.pull_request.title}}
        elif [ ! -f "/home/runner/work/backend.ai/backend.ai/changes/temp.txt" ] && [ ! -f "/home/runner/work/backend.ai/backend.ai/changes/*.md" ]; then
          echo "Error: temp.txt and .md file both not exist"
          exit 1
        fi